spring:
  application:
    name: currency-conversion-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
server:
  port: 8100
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761